### ISSUE TITLE
Override native IE10+ placeholder behavior, disappearing text on focus

### ISSUE THREAD

**Issue by danielHalan** [mathiasbynens/jquery-placeholder#204] opened 2014-04-16 15:36 UTC
modern IE native placeholder feature clears the text on Focus, which isnt so good when using JS to pre-select a textbox.

Is there a way to override this behavior? if not, would be a nice feature.

**Comment by erikmontes** [comment] 2015-03-07 20:48
I'm going to say this is related to #92

**Comment by gabskoro** [comment] 2015-04-09 14:43
Argh, I need this feature now :)

**Comment by amerikan** [comment] 2015-09-24 02:49
Closing, duplicate of #92

**Closed by amerikan** 2015-09-24 02:49 UTC
Labels: feature
