### ISSUE TITLE
autocomplete selected, Password box still shows placeholder text

### ISSUE THREAD

**Issue by onesummer** [mathiasbynens/jquery-placeholder#78] opened 2012-05-21 13:31 UTC
Not a dealbreaker, but thought I'd mention this.

During development I leave autocomplete on my login page so I don't have to constantly retype my username/password for testing. Well, if I click in the username field and select a previous username I've used to login with before, it does actually fill in my password, however, the placeholder text 'Password' still remains. So I cantechnically hit login and it will log me in fine, but just visually speaking I would have liked it to have shown the dots for the password box and not the placeholder text since the field does in fact hold a value. If the cursor then focuses on the password box, the dots then show properly. 

experienced this in IE8.

overall though, best placeholder plugin I've used (and I've tried at least a handful of them). thanks!

**Comment by amerikan** [comment] 2015-09-24 03:15
Closing as duplicate of #14

**Closed by amerikan** 2015-09-24 03:15 UTC
