### ISSUE TITLE
Keep placeholder class when removing input value on a blur event 

### ISSUE THREAD

**Issue by pengill** [mathiasbynens/jquery-placeholder#211] opened 2014-05-28 14:17 UTC
If another event handler is attached to the input 'blur' event that clears out the input value inside it the plugin removes the 'placeholder' class unnecessary.

Example:
```html
<input type="text" name="text1" placeholder="Type something…">
```
setup a new new event handler on blur that clears the value

```js
$("input[name='text1']").on("blur", function() {
     $(this).val("");
});
```

The results of this: the placeholder value will still appear in the input but the 'placeholder' class got removed.

**Comment by xsbear** [comment] 2015-04-03 03:38
the same issue with you

**Comment by amerikan** [comment] 2015-09-24 02:58
Duplicate of #92

**Closed by amerikan** 2015-09-24 02:58 UTC
