### ISSUE TITLE
Placeholders not appearing for password input

### ISSUE THREAD

**Issue by ajbeaven** [mathiasbynens/jquery-placeholder#267] opened 2015-09-21 01:53 UTC
When I use jquery.placeholder.js on IE9, placeholders do not appear for password inputs, however when I used the minified versions, it does work correctly.

At least one commit I found only updated the minified version and not the non-minified version though I'm unsure if there are others that have been missed:

https://github.com/mathiasbynens/jquery-placeholder/commit/b3055b0b5eaef2b89b22e0898fb8ab930425b491

jquery-placeholder version: v2.1.2
jquery vesion: v1.11.1
browser version: IE9 (emulated)

**Comment by amerikan** [comment] 2015-09-23 21:58
@ajbeaven I have minified latest version which is v2.1.3. Please test, let me know if the issue still persists, otherwise I'll close this issue in a few days.

**Comment by ajbeaven** [comment] 2015-09-23 22:10
Sorry, I think you did it the wrong way around. The _minified_ version was the one that worked. If you check out the commit for https://github.com/mathiasbynens/jquery-placeholder/commit/b3055b0b5eaef2b89b22e0898fb8ab930425b491 you'll see that there were no changes to the non-minified version. The change you've just done to re-minify has since broken the minified version.

I wonder if it's better to take pull requests that only change jquery.placeholder.js and then manually update jquery.placeholder.min.js yourself to stop issues like this? That also protects against people slipping in malicious changes to minified commit. Just a thought - I'm not hugely experienced with git and so am not sure if this is common practice, but it makes sense to me ;)

**Comment by ajbeaven** [comment] 2015-09-23 22:12
Sorry, I should also mention that this is only apparent when you use IE9 in emulation mode, as per the comment attached to that commit.

**Comment by amerikan** [comment] 2015-09-23 22:13
@ajbeaven then something in latest version broke it... As far as minification, I'm the only one who minifies it and I don't accept PR's with minifications.

I'll test it out to see if I can reproduce the bug you're encountering.

**Comment by amerikan** [comment] 2015-09-23 23:29
@ajbeaven Using the latest code, I'm able to run the [demo page](https://mathiasbynens.github.io/jquery-placeholder/) just fine with passwords. 

Windows 7, IE 9 simulated in IE10.

The only difference is that the demo page is using [jQuery 1.10.2](https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js)

See screenshot:

![screen shot 2015-09-23 at 4 25 08 pm](https://cloud.githubusercontent.com/assets/179356/10061661/b1c6116e-620f-11e5-973c-c74ecfd87722.png)

So you can try to things if you're already using latest minified version. 1. Try running the demo page under your environment where you are seeing this bug to see if it works there. 2. Try using jquery 1.10.2 just to see if jQuery version is causing it. Thanks.

**Comment by ajbeaven** [comment] 2015-09-24 00:48
Well that's weird. Move type=tel and type=password outside of their container divs (so they're direct direct children of the form) and you'll be able to reproduce the problem. This doesn't happen with the old minified version I was using previously.

![capture](https://cloud.githubusercontent.com/assets/657201/10062755/43ac8586-62ba-11e5-90d2-65fac692c7aa.PNG)

**Comment by amerikan** [comment] 2015-09-24 04:02
I've simplified the [demo](https://mathiasbynens.github.io/jquery-placeholder/) page and can now reproduce.

**Comment by amerikan** [comment] 2015-09-24 04:07
@ajbeaven Do you know which was the minified version you were using when it was working?

**Comment by ajbeaven** [comment] 2015-09-24 04:11
I think it was the one in the commit referenced up the top: https://github.com/mathiasbynens/jquery-placeholder/blob/b3055b0b5eaef2b89b22e0898fb8ab930425b491/jquery.placeholder.min.js

**Comment by jlmainguy** [comment] 2015-10-15 04:28
Hi, I am using the latest minified version and I'm also experiencing this bug in IE8-9 on my website as well as on the demo itself. I'm using VMs on Virtual Box on OSX. IE9 on Win7 and IE8 on XP.

<img width="838" alt="placeholder-1" src="https://cloud.githubusercontent.com/assets/5431960/10504825/8eaa1b6a-72d3-11e5-8705-d71086dbde63.png">
<img width="835" alt="placeholder-2" src="https://cloud.githubusercontent.com/assets/5431960/10504826/8eb7369c-72d3-11e5-92cf-ffe88ab4326e.png">

**Comment by amerikan** [comment] 2015-10-16 11:45
@jlmainguy this is a known issue. Please use older version of plugin. I will try to get this fixed soon.

**Comment by amerikan** [comment] 2015-11-04 23:28
Hmmm, ok so this bug was introduce in this commit on this line https://github.com/mathiasbynens/jquery-placeholder/commit/4902ebee327a42cc172e0e7fe8800257ef287087#diff-fdadbd15fd58f358cf360bf123640125R168

**Comment by amerikan** [comment] 2015-11-05 17:58
@jlmainguy @ajbeaven I just push a fix into `jquery.placeholder.js` in the **gh-pages** branch, can you grab it and test to see if this issue is resolved? I tested it and it now works for me.

**Comment by amerikan** [comment] 2015-11-10 19:51
This has been fixed in v2.2.0.

**Closed by amerikan** 2015-11-10 19:51 UTC
Labels: bug
